### ISSUE TITLE
RC Link

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/fmLTPBR_design#8]
@philipbaileynar  - why are non of the links on the banner working? More or less a bunch of 404s? Whats the deal?

![Screen Shot 2020-05-05 at 10 05 11 AM](https://user-images.githubusercontent.com/34071692/81094122-e9bf2900-8eb7-11ea-8c2f-5f0648a0d21e.png)

**Comment by joewheaton** [comment]
They have changed since M@ wrote template. @MattReimer am I right in thinking we can update template or do we need to fix these on each site?

**Comment by MattReimer** [comment]
This should be handled in the main template. Let me take a look and see if I can figure. it out.

**Comment by MattReimer** [comment]
Ok, so here's the deal:

We need to upgrade to Jekyll4.0 before we can start sharing `_config.yml` data from the root. I'm working on it but it might be a while since there are some compatibility issues I won't bore you with.

for now the (really dumb) solution is for every single site to have its own copy of `topmenu`. You can get it from here:

https://github.com/Riverscapes/riverscapes-website/blob/master/_config.yml

for now the quick fix is just to put this in your `_config.yml` file. Make sure to match the indentation. `topmenu` should be at the same level as `sideMenu` above it.

I know this isn't sustainable and it's a real pain if the root site changes. Hopefully the 4.0 upgrade can happen soon.

**Comment by nick4rivers** [comment]
Thanks @MatthewMeier , this is good for now
